import type { WebSocket } from "ws";

import type { Command } from "../game/command";
import type { GameEvent } from "../game/event";
import {
    getGameStateView,
} from "../game/view";
import {
    executeCommand,
    type Room,
} from "./room";
import type { Actor } from "../game/rules";

export function handleConnection(
    socket: WebSocket,
    room: Room,
) {
    // Initially, the connection has no identity. 
    let actor: Actor = {
        type: "UNASSIGNED",
    };

    // Send the initial game state to the new connection.
    sendState(
        socket,
        room,
        actor,
    );

    // On every message, handle the command and update the connection's identity if it changes.
    socket.on("message", raw => {
        actor = handleMessage(
            socket,
            room,
            actor,
            raw,
        );
    });

    socket.on("close", () => {
        removeConnection(
            socket,
            room,
            actor,
        );
    });
}

function handleMessage(
    socket: WebSocket,
    room: Room,
    actor: Actor,
    raw: WebSocket.RawData
): Actor {

    // Command parsing and validation
    const command = parseCommand(raw);
    if (command === null) {
        sendError(
            socket,
            "INVALID_COMMAND",
            "Invalid command.",
        );

        return actor;
    }

    // Check if the command can be executed by this connection.
    if (!canExecute(socket,room,command)) {
        return actor;
    }

    // If so, execute the command and update the game state.
    const result = executeCommand(
        room,
        actor,
        command,
    );

    if (result.type === "ERROR") {
        sendError(
            socket,
            result.error.code,
            result.error.message,
        );

        return actor;
    }

    // Handle the events generated by the command, updating the connection's identity if necessary.
    const newActor = handleEvents(
        socket,
        room,
        actor,
        result.events,
    );

    broadcastState(room);

    return newActor;
}

function canExecute(
    socket: WebSocket,
    room: Room,
    command: Command,
): boolean {

    // If the command is to become a player, check if the desired name is already connected.
    if (command.type === "BECOME_PLAYER") {
        const name = command.desiredName
            .trim()
            .toLowerCase();

        const existingSocket =
            room.connections.players.get(name);

        if (existingSocket !== undefined && existingSocket !== socket) {
            sendError(
                socket,
                "PLAYER_ALREADY_CONNECTED",
                "That player is already connected.",
            );

            return false;
        }
    }

    return true;
}

function handleEvents(
    socket: WebSocket,
    room: Room,
    actor: Actor,
    events: GameEvent[],
): Actor {
    for (const event of events) {

        // Update the connection's identity if the event changes it.
        switch (event.type) {
            case "HOST_BECAME":
                actor = {
                    type: "HOST",
                };

                room.connections.host = socket;
                break;

            case "PLAYER_BECAME":
                actor = {
                    type: "PLAYER",
                    name: event.player.name,
                };

                room.connections.players.set(
                    event.player.name
                        .trim()
                        .toLowerCase(),
                    socket,
                );
                break;
        }
    }

    return actor;
}

function sendState(
    socket: WebSocket,
    room: Room,
    actor: Actor,
) {
    socket.send(JSON.stringify({
        type: "STATE",
        state: getGameStateView(
            room.game,
            actor,
        ),
        actor: actor,
    }));
}

function sendError(
    socket: WebSocket,
    code: string,
    message: string,
) {
    socket.send(JSON.stringify({
        type: "ERROR",
        error: {
            code,
            message,
        },
    }));
}

function broadcastState(
    room: Room,
) {
    if (room.connections.host !== null) {
        sendState(
            room.connections.host,
            room,
            {
                type: "HOST",
            },
        );
    }

    for (
        const [name, socket]
        of room.connections.players
    ) {
        sendState(
            socket,
            room,
            {
                type: "PLAYER",
                name,
            },
        );
    }
}

function removeConnection(
    socket: WebSocket,
    room: Room,
    actor: Actor,
) {
    switch (actor.type) {
        case "HOST":
            if (room.connections.host === socket) {
                room.connections.host = null;
            }
            break;

        case "PLAYER": {
            const key = actor.name
                .trim()
                .toLowerCase();

            if (room.connections.players.get(key) === socket) {
                room.connections.players.delete(key);
            }

            break;
        }

        case "UNASSIGNED":
            break;
    }
}

function parseCommand(
    raw: WebSocket.RawData,
): Command | null {
    try {
        const value = JSON.parse(
            raw.toString(),
        );

        return value as Command;
    } catch {
        return null;
    }
}