// These are the various events that can be generated by commands.
// They are applied to the game state in `server/room.ts` using the `applyEvent` function.
// They are also sent to the clients.

import { Vote } from "./model/game-state.js";
import type { Player } from "./model/player.js";

export type GameEvent =
    | {
        type: "HOST_BECAME";
    }
    | {
        type: "HOST_DESTROYED";
    }
    | {
        type: "PLAYER_BECAME";
        player: Player;
    }
    | {
        type: "PLAYER_DESTROYED";
        playerId: string;
    }
    | {
        type: "VOTE_CAST";
        playerId: string;
        vote: Vote;
    }
    | {
        type: "INPUT_PAGE_ADVANCED";
        playerId: string;
    }
    | {
        type: "GAME_ADVANCED";
    }
    | {
        type: "GAME_REGRESSED";
    }