// These are the various events that can be generated by commands.
// They are applied to the game state in `server/room.ts` using the `applyEvent` function.
// They are also sent to the clients.

import type { Player } from "./model/player";

export type GameEvent =
    | {
        type: "HOST_BECAME";
    }
    | {
        type: "HOST_DESTROYED";
    }
    | {
        type: "PLAYER_BECAME";
        player: Player;
    }
    | {
        type: "PLAYER_DESTROYED";
        playerId: string;
    }
    | {
        type: "COUNTER_INCREMENTED";
    }
    | {
        type: "COUNTER_DECREMENTED";
    }
    | {
        type: "COUNTER_RESET";
    };